name: "book"

on:
  push:
    branches:
      - main


permissions:
    checks: write
    contents: read

jobs:


  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/pdoc@v0.1.72
        with:
          source-folder: src/tschm


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.72

      - uses: tschm/cradle/actions/coverage@v0.1.72
        with:
          tests-folder: src/tests
          source-folder: src/tschm
          
  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc]

    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.72
        with:
          title: "Numpy Flight"
          links: |
            {
              "API": "./pdoc/index.html"
            }
