name: "book"

on:
  push:
    branches:
      - main


permissions:
    checks: write
    contents: read

jobs:


  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.69

      - uses: tschm/cradle/actions/pdoc@v0.1.69
        with:
          source-folder: src/tschm


  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.69

      - uses: tschm/cradle/actions/coverage@v0.1.69
        with:
          tests-folder: src/tests
          source-folder: src/tschm

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.69

      - uses: tschm/cradle/actions/jupyter@v0.1.69

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    environment:
      name: github-pages

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Upload the book
        uses: tschm/cradle/actions/book@v0.1.71
