name: pre-commit

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment"
        uses: cvxgrp/.github/actions/environment@v2.2.8

      - uses: cvxgrp/.github/actions/deptry@v2.2.8
        with:
          source-folder: src/tschm

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: cvxgrp/.github/actions/pre-commit@v2.2.8
