name: pre-commit

on:
  push:

permissions:
  checks: write
  contents: read

jobs:
  deptry:
    runs-on: ubuntu-latest
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.75

      - uses: tschm/cradle/actions/deptry@v0.1.75
        with:
          source-folder: src/tschm

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: tschm/cradle/actions/pre-commit@v0.1.75
